<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>LANShareManager.CLI</RootNamespace>
    <AssemblyName>LANShareManager</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LANShareManager.Core\LANShareManager.Core.csproj" />
    <ProjectReference Include="..\LANShareManager.Infrastructure\LANShareManager.Infrastructure.csproj" />
  </ItemGroup>
</Project>
